
package vista;


public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        btnMenuEquipo = new javax.swing.JMenuItem();
        btnParte = new javax.swing.JMenuItem();
        btnSoftware = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnDTUbicacion = new javax.swing.JMenuItem();
        btnDTCuentadante = new javax.swing.JMenuItem();
        btnDTProveedor = new javax.swing.JMenuItem();
        btnEquipo = new javax.swing.JMenuItem();
        btnPartevista = new javax.swing.JMenuItem();
        btnSoftwarelist = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        jMenu1.setText("Agregar");

        jMenuItem1.setText("Ubicacion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cuentadante");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Provedor");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        btnMenuEquipo.setText("Equipo");
        btnMenuEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEquipoActionPerformed(evt);
            }
        });
        jMenu1.add(btnMenuEquipo);

        btnParte.setText("Parte");
        btnParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParteActionPerformed(evt);
            }
        });
        jMenu1.add(btnParte);

        btnSoftware.setText("Sofrware");
        btnSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoftwareActionPerformed(evt);
            }
        });
        jMenu1.add(btnSoftware);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Base");

        btnDTUbicacion.setText("Ubicacion");
        btnDTUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDTUbicacionActionPerformed(evt);
            }
        });
        jMenu2.add(btnDTUbicacion);

        btnDTCuentadante.setText("Cuentadante");
        btnDTCuentadante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDTCuentadanteActionPerformed(evt);
            }
        });
        jMenu2.add(btnDTCuentadante);

        btnDTProveedor.setText("Proveedor");
        btnDTProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDTProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(btnDTProveedor);

        btnEquipo.setText("Equipo");
        btnEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoActionPerformed(evt);
            }
        });
        jMenu2.add(btnEquipo);

        btnPartevista.setText("Parte");
        btnPartevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartevistaActionPerformed(evt);
            }
        });
        jMenu2.add(btnPartevista);

        btnSoftwarelist.setText("Software");
        btnSoftwarelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoftwarelistActionPerformed(evt);
            }
        });
        jMenu2.add(btnSoftwarelist);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MenuAgregarUbicacion maUbicacion=new MenuAgregarUbicacion();
        maUbicacion.setVisible(true);
        jDesktopPane1.add(maUbicacion);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MenuCuentadante menucuentadante=new MenuCuentadante();
        menucuentadante.setVisible(true);
        jDesktopPane1.add(menucuentadante);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        MenuProveedor menuproveedor=new MenuProveedor();
        menuproveedor.setVisible(true);
        jDesktopPane1.add(menuproveedor);
        
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnDTCuentadanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDTCuentadanteActionPerformed
        // TODO add your handling code here:
        ListaCuentadante lstcuentadante=new ListaCuentadante();
        lstcuentadante.setVisible(true);
        jDesktopPane1.add(lstcuentadante);
    }//GEN-LAST:event_btnDTCuentadanteActionPerformed

    private void btnDTUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDTUbicacionActionPerformed
        // TODO add your handling code here:
        ListaUbicacion lstubi=new ListaUbicacion();
        lstubi.setVisible(true);
        jDesktopPane1.add(lstubi);
    }//GEN-LAST:event_btnDTUbicacionActionPerformed

    private void btnDTProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDTProveedorActionPerformed
        // TODO add your handling code here:
        ListaProveedor lstproveedor=new ListaProveedor();
        lstproveedor.setVisible(true);
        jDesktopPane1.add(lstproveedor);
    }//GEN-LAST:event_btnDTProveedorActionPerformed

    private void btnMenuEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEquipoActionPerformed
        // TODO add your handling code here:
        MenuEquipo menuequipo=new MenuEquipo();
        menuequipo.setVisible(true);
        jDesktopPane1.add(menuequipo);
    }//GEN-LAST:event_btnMenuEquipoActionPerformed

    private void btnEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoActionPerformed
        // TODO add your handling code here:
        ListaEquipo lstequpo=new ListaEquipo();
        lstequpo.setVisible(true);
        jDesktopPane1.add(lstequpo);
    }//GEN-LAST:event_btnEquipoActionPerformed

    private void btnParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParteActionPerformed
        // TODO add your handling code here:
        MenuParte menuparte=new MenuParte();
        menuparte.setVisible(true);
        jDesktopPane1.add(menuparte);
    }//GEN-LAST:event_btnParteActionPerformed

    private void btnPartevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartevistaActionPerformed
        // TODO add your handling code here:
        ListaParte lstparte =new ListaParte();
        lstparte.setVisible(true);
        jDesktopPane1.add(lstparte);
    }//GEN-LAST:event_btnPartevistaActionPerformed

    private void btnSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoftwareActionPerformed
        // TODO add your handling code here:
        MenuSoftware menusoftware=new MenuSoftware();
        menusoftware.setVisible(true);
        jDesktopPane1.add(menusoftware);
    }//GEN-LAST:event_btnSoftwareActionPerformed

    private void btnSoftwarelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoftwarelistActionPerformed
        // TODO add your handling code here:
        ListaSoftware lstsoft=new ListaSoftware();
        lstsoft.setVisible(true);
        jDesktopPane1.add(lstsoft);
    }//GEN-LAST:event_btnSoftwarelistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnDTCuentadante;
    private javax.swing.JMenuItem btnDTProveedor;
    private javax.swing.JMenuItem btnDTUbicacion;
    private javax.swing.JMenuItem btnEquipo;
    private javax.swing.JMenuItem btnMenuEquipo;
    private javax.swing.JMenuItem btnParte;
    private javax.swing.JMenuItem btnPartevista;
    private javax.swing.JMenuItem btnSoftware;
    private javax.swing.JMenuItem btnSoftwarelist;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
