
package vista;

import controlador.DAO;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.cls_cuentadante;
import modelo.cls_equipo;
import modelo.cls_equipovista;
import modelo.cls_proveedor;
import modelo.cls_ubicacion;


public class MenuEquipo extends javax.swing.JInternalFrame {
    DAO dao =new DAO();
    

    /**
     * Creates new form MenuEquipo
     */
    public MenuEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        comboDia = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        comoboAno = new javax.swing.JComboBox<>();
        txtGarantia = new javax.swing.JTextField();
        txtClasificacion = new javax.swing.JTextField();
        comboCuentadante = new javax.swing.JComboBox<>();
        comboUbicacion = new javax.swing.JComboBox<>();
        comboProveedor = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtSerial = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Equipo ID:");

        jLabel2.setText("Serial:");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("Tipo:");

        jLabel6.setText("Fecha ");

        jLabel7.setText("Garantia");

        jLabel8.setText("Clasificacion");

        jLabel9.setText("Cuentadante");

        jLabel10.setText("Ubicacion");

        jLabel11.setText("Proveedor");

        jLabel12.setText("Dia");

        jLabel13.setText("Mes");

        jLabel14.setText("Año");

        txtID.setEditable(false);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGarantia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboProveedor, 0, 222, Short.MAX_VALUE)
                                    .addComponent(comboUbicacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboCuentadante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtClasificacion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel12)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13)
                                                .addGap(43, 43, 43)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(comoboAno, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(7, 7, 7))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(26, 26, 26))))
                                    .addComponent(txtSerial)
                                    .addComponent(txtMarca))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscar)
                    .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnEditar)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comoboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboCuentadante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        llenarCombobox();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
    
        String Serial=txtSerial.getText();
        String Marca=txtMarca.getText();
        String Modelo =txtModelo.getText();
        String Tipo=txtTipo.getText();
        LocalDate FechaCompra=LocalDate.of(Integer.parseInt(comoboAno.getSelectedItem().toString()),Integer.parseInt(comboMes.getSelectedItem().toString()),Integer.parseInt(comboDia.getSelectedItem().toString()));
        int Garantia=Integer.parseInt(txtGarantia.getText());
        String Clasificacion=txtClasificacion.getText();
        String CuentadanteNombre=(comboCuentadante.getSelectedItem().toString());
        String UbicacionNombre=comboUbicacion.getSelectedItem().toString();
        String ProveedorNombre=comboProveedor.getSelectedItem().toString();
        
        int CuentadanteID=0;
        int UbicacionID=0;
        int ProveedorID=0;
        
        ArrayList <cls_cuentadante> lstCuentadante=dao.ListaCuentadante();
        ArrayList <cls_ubicacion> lstUbicacion=dao.ListaUbicacion();
        ArrayList <cls_proveedor> lstProveedor=dao.Listaproveedor();
        
        for (cls_cuentadante cuentadante : lstCuentadante) {
            if(cuentadante.getNombre().equals(CuentadanteNombre)){
                CuentadanteID=cuentadante.getCuentadanteid();
                
            }
        }
        for (cls_ubicacion ubicacion : lstUbicacion) {
            if(ubicacion.getNombre().equals(UbicacionNombre)){
                UbicacionID= ubicacion.getUbicacionid();
            }    
        }
        for (cls_proveedor proveedor: lstProveedor){
            if (proveedor.getRazonsocial().equals(ProveedorNombre)){
                ProveedorID=proveedor.getProveedorid();
            }
        }
        
        
        
        
        if(txtClasificacion.getText().equals("")||txtGarantia.getText().equals("")||txtMarca.getText().equals("")||txtModelo.getText().equals("")||txtSerial.getText().equals("")||txtTipo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite Bien los campos");
        }else{
            
            cls_equipo equipo=new cls_equipo(Serial, Marca, Modelo, Tipo, FechaCompra, Garantia, Clasificacion, CuentadanteID, UbicacionID, ProveedorID);
            dao.CrearEquipo(equipo);
            
        }
        Limpiar();
       
        
        
            
            
            
            
            
        
        

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String Serial=txtSerial.getText();
        cls_equipovista equipo= dao.BuscarEquipo(Serial);
        if (equipo!=null){
        txtID.setText(""+equipo.getEquipoid());
        txtSerial.setText(equipo.getSerial());
        txtMarca.setText(equipo.getMarca());
        txtModelo.setText(equipo.getModelo());
        txtTipo.setText(equipo.getTipo());
        
        int dia =equipo.getFechacompra().getDayOfMonth();
        int mes =equipo.getFechacompra().getMonthValue();
        int ano =equipo.getFechacompra().getYear();
        
        comboDia.setSelectedIndex(dia-1);
        comboMes.setSelectedIndex(mes-1);
        comoboAno.setSelectedIndex(ano-2010);
        
        txtGarantia.setText(""+equipo.getGarantia());
        txtClasificacion.setText(equipo.getClasificacion());
        
        comboCuentadante.setSelectedItem(equipo.getCuentadante());
        comboUbicacion.setSelectedItem(equipo.getUbicacion());
        comboProveedor.setSelectedItem(equipo.getProveedor());
        }
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int ID=Integer.parseInt(txtID.getText());
        String Serial=txtSerial.getText();
        String Marca=txtMarca.getText();
        String Modelo=txtModelo.getText();
        String Tipo=txtTipo.getText();
        
        LocalDate Fecha=LocalDate.of(Integer.parseInt(comoboAno.getSelectedItem().toString()),Integer.parseInt(comboMes.getSelectedItem().toString()),Integer.parseInt(comboDia.getSelectedItem().toString()));
        int Garantia=Integer.parseInt(txtGarantia.getText());
        String Clasificacion=txtClasificacion.getText();
        
        String NombreCuentadante=comboCuentadante.getSelectedItem().toString();
        String NombreUbicacion=comboUbicacion.getSelectedItem().toString();
        String NombreProveedor=comboProveedor.getSelectedItem().toString();
        
        ArrayList <cls_cuentadante> lstCuentadante=dao.ListaCuentadante();
        ArrayList <cls_ubicacion> lstUbicacion=dao.ListaUbicacion();
        ArrayList <cls_proveedor> lstProveedor=dao.Listaproveedor();
        
        int CuentadanteID=0;
        int UbicacionID=0;
        int ProveedorID=0;
        
        
        for (cls_cuentadante cuentadante : lstCuentadante) {
            if (cuentadante.getNombre().equals(NombreCuentadante)){
                CuentadanteID=cuentadante.getCuentadanteid();
            }        
        }
        for (cls_ubicacion ubicacion : lstUbicacion) {
            if(ubicacion.getNombre().equals(NombreUbicacion)){
                UbicacionID=ubicacion.getUbicacionid();
            }
            
        }
        for (cls_proveedor proveedor : lstProveedor) {
            if(proveedor.getRazonsocial().equals(NombreProveedor)){
                ProveedorID=proveedor.getProveedorid();
            }
            
        }
        
        cls_equipo equipo=new cls_equipo(ID, Serial, Marca, Modelo, Tipo, Fecha, Garantia, Clasificacion, CuentadanteID, UbicacionID, ProveedorID);
        dao.ActualizarEquipo(equipo);
        
        Limpiar();
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int ID=Integer.parseInt(txtID.getText());
        String Serial=txtSerial.getText();
        String Marca=txtMarca.getText();
        String Modelo=txtModelo.getText();
        String Tipo=txtTipo.getText();
        
        LocalDate Fecha=LocalDate.of(Integer.parseInt(comoboAno.getSelectedItem().toString()),Integer.parseInt(comboMes.getSelectedItem().toString()),Integer.parseInt(comboDia.getSelectedItem().toString()));
        int Garantia=Integer.parseInt(txtGarantia.getText());
        String Clasificacion=txtClasificacion.getText();
        
        String NombreCuentadante=comboCuentadante.getSelectedItem().toString();
        String NombreUbicacion=comboUbicacion.getSelectedItem().toString();
        String NombreProveedor=comboProveedor.getSelectedItem().toString();
        
        ArrayList <cls_cuentadante> lstCuentadante=dao.ListaCuentadante();
        ArrayList <cls_ubicacion> lstUbicacion=dao.ListaUbicacion();
        ArrayList <cls_proveedor> lstProveedor=dao.Listaproveedor();
        
        int CuentadanteID=0;
        int UbicacionID=0;
        int ProveedorID=0;
        
        
        for (cls_cuentadante cuentadante : lstCuentadante) {
            if (cuentadante.getNombre().equals(NombreCuentadante)){
                CuentadanteID=cuentadante.getCuentadanteid();
            }        
        }
        for (cls_ubicacion ubicacion : lstUbicacion) {
            if(ubicacion.getNombre().equals(NombreUbicacion)){
                UbicacionID=ubicacion.getUbicacionid();
            }
            
        }
        for (cls_proveedor proveedor : lstProveedor) {
            if(proveedor.getRazonsocial().equals(NombreProveedor)){
                ProveedorID=proveedor.getProveedorid();
            }
            
        }
        
        cls_equipo equipo=new cls_equipo(ID, Serial, Marca, Modelo, Tipo, Fecha, Garantia, Clasificacion, CuentadanteID, UbicacionID, ProveedorID);
        dao.EliminarEquipo(equipo);
        
        Limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    private void llenarCombobox( ){
        ArrayList <cls_cuentadante> lstCuentadante=dao.ListaCuentadante();
        ArrayList <cls_ubicacion> lstUbicacion=dao.ListaUbicacion();
        ArrayList <cls_proveedor> lstProveedor=dao.Listaproveedor();
        int fechainicio=2010;
        LocalDate fechaactual=LocalDate.now();
        
        
        for (cls_cuentadante cuentadante : lstCuentadante) {
            comboCuentadante.addItem(cuentadante.getNombre());
            
            
        }
        for (cls_ubicacion ubicacion : lstUbicacion) {
            comboUbicacion.addItem(ubicacion.getNombre());
            
        }
        for (cls_proveedor proveedor : lstProveedor) {
            comboProveedor.addItem(proveedor.getRazonsocial());  
            
        }
        for (int i = 1; i < 32; i++) {
            comboDia.addItem(""+i);
            
        }
        for (int i = 1; i < 13; i++) {
            comboMes.addItem(""+i);
            
        }
        while(fechainicio<=fechaactual.getYear()){
            comoboAno.addItem(""+fechainicio);
            fechainicio+=1;
        }
        
        
        
        
    }
            
    
    private void Limpiar (){
        txtClasificacion.setText("");
        txtGarantia.setText("");
        txtID.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtSerial.setText("");
        txtTipo.setText("");
     
        
       
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comboCuentadante;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JComboBox<String> comboUbicacion;
    private javax.swing.JComboBox<String> comoboAno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
